# Generated by Django 3.2.10 on 2021-12-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='filename',
            new_name='file',
        ),
    ]
