# Generated by Django 3.2.10 on 2021-12-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire', '0003_rename_contrubutors_work_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
